### ISSUE TITLE
fix: css for the banner scales wrong. It take sup unneeded space

### ISSUE THREAD

**Issue by oj-lappi** [Datateknologerna-vid-Abo-Akademi/date-website#100]
**Is your fix request related to a problem?**  
Consider creating a bug report. You can also describe why it should be a fix and not a bug.

**Describe the solution you'd like**  

The black area on the home page should scale with its content. It seems to now occupy a fixed height (based on the screen height?) instead of scaling properly.

**Additional context**

**Comment by andreedd** [comment]
I've tried to scale the Albin SVG using media queries, not the best result.
If someone know any good ways to make the Albin SVG responsive, feel free to help.

**Comment by jaspnas** [comment]
Scales well enough on most devices
