### ISSUE TITLE
feat: integrate google calendar

### ISSUE THREAD

**Issue by Faagerholm** [Datateknologerna-vid-Abo-Akademi/date-website#113]
Datateknologera has had a google calendar for many years but has not been used for a long time. 

If we would integrate this into our webpage we would could get more visibility for our events. 

I know also that KK has used a google calendar in the past, maybe this is something they also would be interested in. 
We should have a chat with them to see if it's something they would be interested in.

**Comment by jaspnas** [comment]
Not planned for now, closing as stale
