### ISSUE TITLE
fix: Make accounts inactive when paid membership runs out

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#123]
**Is your fix request related to a problem?**  
Consider creating a bug report. You can also describe why it should be a fix and not a bug.

The board has requested a feature that accounts will become inactive if someone haven't paid their membership

**Describe the solution you'd like**  

Activate the account when membership is paid
Deactivate the account if membership isn't paid

Maybe display that membership is not paid to the person trying to log in if deactivated?

**Additional context**

**Comment by jaspnas** [comment]
Membership card turns red atm. Probably more work than it's worth for now to deactivate the accounts
