### ISSUE TITLE
feat: LDAP Authentication service

### ISSUE THREAD

**Issue by oj-lappi** [Datateknologerna-vid-Abo-Akademi/date-website#13]
- [X] Service which returns auth or no auth
 - [X] Crypted channel to authentication service
 - [ ] Service running on special.abo.fi

**Comment by osoderholm** [comment]
Current, extremely hacky, way of authenticating against oldwww.abo.fi will probably not work after 2020-01-09, as Åbo Akademi will switch to using a new intranet.

**Comment by oj-lappi** [comment]
Yes, but it's a very good kludge ;)

**Comment by Faagerholm** [comment]
This issue will not be implemented for the MVP version. Therefore moving it to the backlog.

**Comment by oj-lappi** [comment]
Decided a while ago not to implement this
