### ISSUE TITLE
feat: blog module

### ISSUE THREAD

**Issue by Faagerholm** [Datateknologerna-vid-Abo-Akademi/date-website#138]
**This is a test issue for our new officials**

The issue is created to get familiar with Github and our workflow in this project.

---
As a new official
- Assign this issue to yourself.
- Write a hello comment to this issue.
- Check our this [wikipedia page](https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/wiki/Meeting-26-11-20) for more information
- Tag this issue when committing to your new feature branch and when you create your final PR.

**Comment by WilliamNylund** [comment]
a hello comment

**Comment by atokos** [comment]
hello, a hello comment

**Comment by rkantero** [comment]
a hello comment to this issue.

**Comment by vsjostro** [comment]
issue to this comment hello

**Comment by hmartola** [comment]
hello

**Comment by jaspnas** [comment]
No longer used, closing as completed.
