### ISSUE TITLE
bug: Previous events are not currently shown

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#152]
**Describe the bug**  
Previous events from past year are currently not shown on production site after new year.

**To Reproduce**  
Check events after new year

**Screenshots**  

![image](https://user-images.githubusercontent.com/33100278/106488581-856bdd00-64bc-11eb-84c9-b6ce243effef.png)

**Desktop, phone (please complete the following information):**  
 - OS: [e.g. iOS, Windows, Linux]

**Additional context**

**Comment by jaspnas** [comment]
Closing as non-issue
