### ISSUE TITLE
bug: Documents can be accessed with direct link.

### ISSUE THREAD

**Issue by Faagerholm** [Datateknologerna-vid-Abo-Akademi/date-website#155]
This might not be a feature that should be available.
This can be accessed by anyone, for example. https://datateknologerna.org/media/skolgangs-material/mt_instructions.pdf

**Comment by andreedd** [comment]
We would still want some files to be a accessed by anyone.
For example: https://datateknologerna.org/media/gulisguide2020/datateknologernas-gulis-guide.pdf is linked to navbar "Gulisguide".
Maybe we want a checkbox for private documents which you have to be logged in to see?

**Comment by Faagerholm** [comment]
Yes, a new field could be added to the Document model class. 
[Here is the class](https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/blob/cf771bdf5387225ad25b9290e1c85d745e6d5219/archive/models.py#L121)

**Comment by andreedd** [comment]
Added in #168 
All media files are now by default private S3 files with a signed url which expires after 1 hr.
Public files are uploaded separately.
