### ISSUE TITLE
bug: Calendar is not visible in mobile view

### ISSUE THREAD

**Issue by pkarvinen** [Datateknologerna-vid-Abo-Akademi/date-website#190]
**Describe the bug**  
The calendar is only available in desktop mode, not the mobile view. This makes it hard to see future events.

**To Reproduce**  
- Open the website on a mobile device
- Scroll down the page to where the calendar should be
- It can't be found
- Enable desktop mode to see the calendar

**Desktop, phone (please complete the following information):**  
 - OS: iOS, Android
 - Browser: All

**Comment by theoabw** [comment]
Fixed in #486
