### ISSUE TITLE
bug: Website crashes when visiting old event

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#194]
**Describe the bug**  

**To Reproduce**  

https://kemistklubben.org/events/anmalning-mm04/

**Screenshots**  

**Desktop, phone (please complete the following information):**  
 - OS: [e.g. iOS, Windows, Linux]

**Additional context**  

Website seems to crash with some kind channel error

INFO HTTP GET /events/anmalning-mm04/ 200 [0.13, 172.22.0.5:36756]
[Failure instance: Traceback: <class 'ValueError'>: No route found for path 'ws/events/anmalning-mm04/'.
/usr/local/lib/python3.8/site-packages/autobahn/websocket/protocol.py:2841:processHandshake
/usr/local/lib/python3.8/site-packages/txaio/tx.py:366:as_future
/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py:191:maybeDeferred
/usr/local/lib/python3.8/site-packages/daphne/ws_protocol.py:72:onConnect
--- <exception caught here> ---
/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py:191:maybeDeferred
/usr/local/lib/python3.8/site-packages/daphne/server.py:200:create_application
/usr/local/lib/python3.8/site-packages/channels/routing.py:54:__call__
/usr/local/lib/python3.8/site-packages/channels/sessions.py:47:__call__
/usr/local/lib/python3.8/site-packages/channels/sessions.py:145:__call__
/usr/local/lib/python3.8/site-packages/channels/sessions.py:169:__init__
/usr/local/lib/python3.8/site-packages/channels/middleware.py:31:__call__
/usr/local/lib/python3.8/site-packages/channels/routing.py:150:__call__
]
INFO WebSocket DISCONNECT /ws/events/anmalning-mm04/ [172.22.0.5:36764]

**Comment by WilliamNylund** [comment]
This seems to have been fixed
