### ISSUE TITLE
fix: stella says that dafny is a problem

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#195]
**Is your fix request related to a problem?**  
When KK are uploading photos, their photos are so big that the memory runs out on the server

**Describe the solution you'd like**  
More memory on server?
Different way of uploading images

**Additional context**  
Django Daphne, not dafny

**Comment by andreedd** [comment]
Sofia agrees that dafny is a problem

**Comment by JoarSabel** [comment]
?

**Comment by jaspnas** [comment]
Duplicate of #186
