### ISSUE TITLE
feat: events from google calendar shows up in website calendar

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#196]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

When a event is added to google calendar it will also show up on website. Or other way around could also work?

**Additional context**

**Comment by nDny** [comment]
Was the idea here that google calendar events are visible in the little html calendar or/and that google calendar events also become "real" events on the website?

**Comment by nDny** [comment]
Integrating google calendar events into our own events becomes a bit more extensive, and since it still would involve manual editing from the admins to adjust every setting/signup for the event etc. IMO it makes sense to keep this as a "show only in calendar" kind of thing.

**Comment by andreedd** [comment]
I think to start with, it would be okay to only display events from google calendar in our html calendar
