### ISSUE TITLE
feat: Make admin cool (again?)

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#201]
**Is your feature request related to a problem? Please describe.**
Current admin page is ugly looking :(

**Describe the solution you'd like**
We want to have a nice looking admin page

**Additional context**
There are a lot of pre made admin templates available

**Comment by JoarSabel** [comment]
The thing goes skkkyyyya: https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/pull/283

Papapapa, skidipapa

**Comment by jaspnas** [comment]
Django 4.0 seems to slightly change how the default admin page looks and apparently adds dark mode

![image](https://user-images.githubusercontent.com/46525212/216840399-3ce9f48e-6339-43bd-88ec-4619b257c093.png)

**Comment by andreedd** [comment]
Probably best to skip this for now, as the new Django versions seems to be quite nice looking as well.
As Danne said, don't fix if aint bork.
