### ISSUE TITLE
feat: Tentarkiv

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#212]
**Is your feature request related to a problem? Please describe.**
Our Documents page would get too cluttered if we uploaded tests here.
Currently we have all archived tests in a zip file at Documents

**Describe the solution you'd like**
We should have a separate page that makes sense for displaying archived tests.

The index page for "tentarkiv" should be a list of folders with the name of the courses.

Example:

* Ingengörsmatematik 1
* Ingengörsmatematik 2
* Signalbehandling
* ...

The folders should be clickable and open files from the courses.

Example:

Click on Ingengörsmatematik 1
*  course test1
*  course test2
*  course assignment 1
* ...

Logged in members should also be able to create new folders and add new material to folders.

**Additional context**
KK also wants this

**Comment by nDny** [comment]
#ddfix
