### ISSUE TITLE
feat: Could start using Materialize css for some things

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#214]
https://materializecss.com

It looks nice.

**Comment by Faagerholm** [comment]
I would say stay to one CSS framework. A collaborative decision should be made as to which framework to use. 

I personally like [Bulma](https://bulma.io/) (a mobile-first framework)
but there is a wide range of good frameworks;
Check this out: https://www.browserstack.com/guide/top-css-frameworks

**Comment by andreedd** [comment]
Yeah probably not a good idea to combine due to conflicting names and such. + more stuff to load.

Was thinking for some components but probably for the better to change completely the framework if it is done.

**Comment by Faagerholm** [comment]
Yea, well.. we (you) could probably start one component/app at a time. I can of course help out a bit if there is something you need help with.

**Comment by nDny** [comment]
We were briefly discussing developing new components with a frontend library (react/vue?) using DRF. Would make a lot of sense for students/people interested in the "frontendier" part of things. 

If we were to do that we could use another css framework for all of the new components.

**Comment by jaspnas** [comment]
Closing as stale, maybe revisit if we wan't to do a major frontend redesign
