### ISSUE TITLE
feat: Image header for posts

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#215]
We could at least for the front-page have a separate image field which is meant to header image for the post.

Could also be used for staticpages, events, & news pages.

Stumbled upon the Norwegian chemists website and got reminded. 
<img width="726" alt="Screenshot 2022-02-10 at 11 03 27" src="https://user-images.githubusercontent.com/33100278/153373573-e993b0cd-6a46-417f-96cc-c81322e1d3be.png">

**Comment by jaspnas** [comment]
Closing as stale
