### ISSUE TITLE
feat: Recurring events yearly timeline page

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#223]
We could have a timeline page which could display months and what events we usually have that month on the year. 

Sort of like our "verksamhetsplan" but could be a little bit more extended as well and nice looking. 

It would be an easy way to get a quick overview of what we usually do during a year.

We could also include our events from our events app there to late compare what was actually arranged and when.

This page would probably be in our events app (or new one?) and be in our located under '/events/timeline-{year}' or something

Styling ideas: https://freefrontend.com/css-timelines/

Example doodle:

<img width="1202" alt="Screenshot 2022-02-17 at 10 18 36" src="https://user-images.githubusercontent.com/33100278/154437690-a3da24e4-d860-4cda-a847-c5c298e96ca6.png">

**Comment by jaspnas** [comment]
Can probably be implemented using a static page
