### ISSUE TITLE
bug: Unable to delete event attendee after moving it in the attendee list

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#238]
**Describe the bug**  
Joar:
tror dock ja hitta en bug 😆man verkar int kuna klick i deletebox på en person efter att man ha flytta folk'

Can't move a person in events admin and then delete

**To Reproduce**  
move attendee and try to delete 

**Sidenote:**
You are able to delete after saving the form

**Comment by WilliamNylund** [comment]
Could not reproduce. @JoarSabel plz show.

**Comment by jaspnas** [comment]
Probaly not a problem as this doesn't break anything. Closing as wontfix for now

**Comment by nDny** [comment]
Maybe better to close it like this and not complete.
