### ISSUE TITLE
add/remove pictures from album

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#25]
Need to be able to add and remove pictures when browsing album as an admin

**Comment by Faagerholm** [comment]
The functionality exists for removing images from an album. 

Also, a user eligible to edit albums"fotograf" should have access to the admin panel where they can find controls for managing pictures.

We should check how to implement adding more records to a given archive.

**Comment by Faagerholm** [comment]
Check out [archive/templates/archive/edit.html](https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/blob/develop/archive/templates/archive/edit.html)

**Comment by Faagerholm** [comment]
A user eligible to edit collections will be redirected to the admin panel, we saw this as a quick solution to the first versions. A better approach can be implemented later.
