### ISSUE TITLE
fix: Fix migrations (and in general) for people developing the project

### ISSUE THREAD

**Issue by nDny** [Datateknologerna-vid-Abo-Akademi/date-website#250]
**Is your fix request related to a problem?**  
No

**Describe the solution you'd like**  
When setting up the project and applying the django migrations, git goes loco. This should not be the case, causes mad confusion and is not proper practices.

**Comment by nDny** [comment]
Comment here is that django development should not be reliant on a "sever clean" state, 

Going forward we really need to manage our django migrations better.

**Comment by jaspnas** [comment]
Closing as fixed
