### ISSUE TITLE
fix: reverse image archive order

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#251]

**Comment by JoarSabel** [comment]
https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/pull/264

Reversed image upload list direction instead to not mess with the existing albums. We should consider doing something about the upload process itself, since that currently is done 8 images at a time.

**Comment by jaspnas** [comment]
> #264
> 
> Reversed image upload list direction instead to not mess with the existing albums. We should consider doing something about the upload process itself, since that currently is done 8 images at a time.

This issue is fixed, uploading addressed in #186
