### ISSUE TITLE
feat: add videos to picture archive

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#252]
Be able to include videos in a picture archive.

This could be a link to the video?
This could embed the video from a external resource?

We could upload the video directly, but I'm not sure we want encourage storing videos since they take up a lot of space.

**Comment by nDny** [comment]
Unless we somehow get our idealistic solution of alternative storage on our own server working I think it's best that we embed/link.


>but I'm not sure we want encourage storing videos since they take up a lot of space.

Unless we somehow use compression and fuck with the quality a lot then we could maybe allow for some storage?
Depends on how much people would use this. One video here and there wouldn't be too bad but if it becomes popular we could quite quickly have a problem.

**Comment by jaspnas** [comment]
Closing as stale/not planned for now, maybe revisit in the future if there is a more concrete plan
