### ISSUE TITLE
feat: Add member role for supporting members

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#256]
Add a separate role for supporting members

So we should have:

- Gulis medlem
- Ordinarie medlem
- Stödjande medlem
- Seniormedlem

**Comment by JoarSabel** [comment]
We have the role, just not the right permissions for them, removed their access to pictures
https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/pull/257

**Comment by JoarSabel** [comment]
Should this be closed, or is there more to be done on the supporting memebers front?

**Comment by jaspnas** [comment]
Should be done, open new more specific issue if something still needs to be done
