### ISSUE TITLE
fix: Don't show event member limit if the isn't one

### ISSUE THREAD

**Issue by jaspnas** [Datateknologerna-vid-Abo-Akademi/date-website#267]
Website currently shows members limit for an event if there isn't a limit on the number of participants.
Change this to hide members limit if this is the case

![image](https://user-images.githubusercontent.com/46525212/213552492-beb919f4-90b4-4f49-87ff-062565a1a6f7.png)

**Comment by Endorias** [comment]
![image](https://user-images.githubusercontent.com/32610653/213698978-9eb34530-4421-4d1c-a80f-037c6295bb41.png)
Do we want the count to show a text instead (like the above image) or completely remove the count from the event detail?

**Comment by andreedd** [comment]
I would say the "ingen begränsning " text is a good way to do it 👍
