### ISSUE TITLE
News style

### ISSUE THREAD

**Issue by Faagerholm** [Datateknologerna-vid-Abo-Akademi/date-website#27]
`/news` lacks any styling in the current version.

Implement with responsiveness in mind for 
`index.html` and `article.html`

place css and js under  
`news/static/news/css` and  
`news/static/news/js`.

---
Note to use predefined colors.  
e.g. `color: var(--primaryColor);`

**Comment by Faagerholm** [comment]
This should be reviewed and closed with no major issues. 

@andreedd, Can you update the status of this issue?

**Comment by andreedd** [comment]
News styling is working as intended and is responsive
