### ISSUE TITLE
bug: Members with Manage groups permission can give themselves any permission. 

### ISSUE THREAD

**Issue by jaspnas** [Datateknologerna-vid-Abo-Akademi/date-website#275]
A logged in user with the permission `auth | grupp | can change group` can change the permissions of his own group to include permissions that he previously didn't have. 

## Steps to reproduce

On your local test deployment, create a new staff group that has the group permissions and add a non-superuser to it. Log in as that user and go to manage the group. You can now add all permissions to yourself.

**Comment by andreedd** [comment]
One quick solution would be to just have one user which manages the permissions and is in that group.

**Comment by jaspnas** [comment]
Would be nice to implement something that checks the users permissions and rejects the request if the user doesn't already have all the permissions. 

This will probably be done later as this is not acute and is probably quite hard to implement.

**Comment by jaspnas** [comment]
Solved by only letting superusers change permissions of a group
