### ISSUE TITLE
Events style

### ISSUE THREAD

**Issue by Faagerholm** [Datateknologerna-vid-Abo-Akademi/date-website#28]
`/events` lacks any styling in the current version.

Implement with responsiveness in mind!
Most of our users will be using mobile to register for an event.

Can we make so that participants list updates with every new attendee added?

place css and js under  
`events/static/events/css`

---
Note to use predefined colors.  
e.g. `color: var(--primaryColor);`

**Comment by andreedd** [comment]
I consider the events styling done for now
