### ISSUE TITLE
fix: Image archive pages load slowly

### ISSUE THREAD

**Issue by jaspnas** [Datateknologerna-vid-Abo-Akademi/date-website#301]
The image collections take long to load (~4.5 seconds/page) on the prod server

This behavior has been observed over multiple days when no-one should be uploading new images. 

### Noticed while investigating

- The speed of the page load seems to depend on how many images are shown on one page. 
- If multiple clients are loading images at the same time the server has full CPU usage on a single core. 
- The issue is not in loading the images themselves, the slow thing is getting image paths from database or generating the html.
- On a local install without S3 the archive seems reasonably fast.

**Comment by jaspnas** [comment]
The part slowing this down seems to be the call to render() in archive/views/picture_detail()

**Comment by andreedd** [comment]
Yes it has been quite slow, i am wondering if this is also the thumbnail library. It seens to be pretty shit 😂
