### ISSUE TITLE
Add ASK information tab to DaTe website

### ISSUE THREAD

**Issue by Stewu1** [Datateknologerna-vid-Abo-Akademi/date-website#345]
Replicate ASK tab like on KKs website, please. @JoarSabel @jaspnas @MirruK 😘
För stysse sidan skulle det vara snyggt om man skulle kunna lägga bilder på alla vid sina namn och kontaktuppgifter.

**Comment by jaspnas** [comment]
ASK has permissions to create the tab. Closing issue.
