### ISSUE TITLE
bug: Uploading pictures to homepage not working

### ISSUE THREAD

**Issue by KuRR221** [Datateknologerna-vid-Abo-Akademi/date-website#354]
Cannot upload pictures via admin page or pictures page.

To reproduce try to upload picture from admin page in album and hit save.

![el mao](https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/assets/81564668/300740a3-9976-4187-8843-f6af1f1fc064)

Desktop, Windows 11, Chrome browser.

**Comment by jaspnas** [comment]
Probably caused by #328
