### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by jaspnas** [Datateknologerna-vid-Abo-Akademi/date-website#411]
Logs are currently deleted when the container is restarted.

We should start using logging drivers (and maybe a service to store the logs in a searchable format) to keep the logs to better be able to find problems with the website

**Comment by andreedd** [comment]
Betterstack, formerly logtail offers 3 day retention for free

https://betterstack.com/logs/pricing

**Comment by jaspnas** [comment]
New Relic also seems to have a pretty generous free tier (although if that's not enough it's going to cost us). Also it's probably like having a bulldozer when all you needed was a shovel

https://newrelic.com/pricing
