### ISSUE TITLE
fix: new calendar width + colors

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#485]
**Is your fix request related to a problem?**  
Calendar is not 100% and colors are not matching our theme

**Describe the solution you'd like**  
Set #calendar width: 100%
Change lightblue colors to matching colors for our theme.

**Additional context**  

<img width="411" alt="Screenshot 2024-01-29 at 10 26 21" src="https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/assets/33100278/6ee383bd-0218-4808-9e28-b644e974a2b0">

**Comment by andreedd** [comment]
Select color could also be different.

Link color on hover could probably also be darkLinkColor

<img width="184" alt="Screenshot 2024-01-29 at 10 32 50" src="https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/assets/33100278/8c9af35e-41f8-4951-bb60-9a94948143a8">
<img width="302" alt="Screenshot 2024-01-29 at 10 32 45" src="https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/assets/33100278/316bfc13-0c40-414b-b994-bc7eb9e9f5f0">

**Comment by theoabw** [comment]
Fixed this issue with #486
