### ISSUE TITLE
bug: Error 405 on /members/logout/

### ISSUE THREAD

**Issue by keanderss** [Datateknologerna-vid-Abo-Akademi/date-website#501]
**Describe the bug**  
Attempting to log out returns error 405. Is this a feature?

**To Reproduce**  
1. Log in to the website
2. Log out
3. Error 405

**Comment by jaspnas** [comment]
Caused by Django only allowing POST requests for security reasons

https://stackoverflow.com/questions/77928535/django-can-login-but-cant-logout-405-method-not-allowed
