### ISSUE TITLE
bug: Event start time on calendar is not displayed correctly

### ISSUE THREAD

**Issue by keanderss** [Datateknologerna-vid-Abo-Akademi/date-website#503]
**Describe the bug**  
Event start time on calendar is displayed as XX:0 instead of XX:00

**To Reproduce**  
1. Create event with start time XX:00
2. View calendar on front page

**Screenshots**  
![image](https://github.com/Datateknologerna-vid-Abo-Akademi/date-website/assets/113473148/2378ee90-014e-4158-bd58-73c82ffec96a)

**Comment by theoabw** [comment]
closed by #510
