### ISSUE TITLE
Change date fields in admin panel for events from text areas to date pickers/calendar pickers

### ISSUE THREAD

**Issue by oj-lappi** [Datateknologerna-vid-Abo-Akademi/date-website#52]
**Is your feature request related to a problem? Please describe.**

Selecting dates will be done fairly often by the stysse when creating events, and we want them to not get hung up on sily little details like this. Writing handcrafted date formats is never the best solution to date input. There should always be at least the option to use a date picker.

**Comment by Faagerholm** [comment]
I found a solution and can implement it to all fields

**Comment by oj-lappi** [comment]
Great!
Sorry I've been inactive for a while, really appreciate that you're pushing all these features in.
