### ISSUE TITLE
config: Ändra innehåll

### ISSUE THREAD

**Issue by idikiwibri** [Datateknologerna-vid-Abo-Akademi/date-website#573]
**Describe the configuration you need**

A clear and concise description of what you need configured.

Ändra rubriken till "Rapportera trakasserier och eventuella brister med jämlikhetsplanen"
Ändra rubriken till "Du kan rapportera trakasserier och brister i jämlikhetsplanen antingen anonymt eller ange din kontaktinformation. Vi tar alla former av trakasserier på allvar och kommer att vidta åtgärder för att upprätthålla en trygg och respektfull miljö för alla medlemmar. 

DaTes trygghetspersoner behandlar alla rapporteringar av trakasserier och tar kontakt till DaTes styrelse och/eller ÅAS trakasseriombud om det så önskas."

**Describe when you need this to be configured**

A date or time frame when you need this configuration to be completed.

Idk, när ni hinner? 

**Additional context**

Add any other context or screenshots about the configuration request here.

**Comment by jaspnas** [comment]
Done, will be deployed with #561
