### ISSUE TITLE
bug: Navbar medlemmar tab items visible to unauthenticated users

### ISSUE THREAD

**Issue by andreedd** [Datateknologerna-vid-Abo-Akademi/date-website#618]
**Describe the bug**  

"Medlemmar" tab dropdown items that should be visible to only authenticated users is visible also to unauthenticated users.

**To Reproduce**  

Hover the navbar "Medlemmar" in incognito mode on DaTes website for example.

**Comment by jaspnas** [comment]
Introduced as a temporary measure when we removed static page linking to the navbar in favor of just using urls. I see this as low priority to fix.

**Comment by nDny** [comment]
One thing I would consider about that is not displaying the admin login page link to the world. Dead Django giveaway :D

**Comment by jaspnas** [comment]
> One thing I would consider about that is not displaying the admin login page link to the world. Dead Django giveaway :D

Considering the server header was "django" until spring I don't think this is anything to worry about unless we want to change what path we use for admin. Most scanning scripts will probably try /admin straight away. :D
