### ISSUE TITLE
feat: Import old images and collections

### ISSUE THREAD

**Issue by Faagerholm** [Datateknologerna-vid-Abo-Akademi/date-website#67]
We would like to have a nice and simple way to import old images from another host or platform. Either by directly referencing the media location or with some other script. No one should need to do this manually for thousands of collections. 

We could discuss if this is a MVP implementation or not.

**Comment by andreedd** [comment]
Added in #168
`archive/s3_upload.py` does the uploading, can be run locally with correct access keys.
`archive/s3_populate_db` populates the database and creates relevant albums by checking images at the S3 endpoint. Need to be run on server.
