### ISSUE TITLE
Deploy Website

### ISSUE THREAD

**Issue by Faagerholm** [Datateknologerna-vid-Abo-Akademi/date-website#8]

**Comment by LinAnt** [comment]
I can probably help out with this. Do we know where yet?

**Comment by Faagerholm** [comment]
We have not decided where to deploy yet, this is a question that the board and members of our association should decide in my opinion.

A meeting should be arranged with the board and interested people so we could get the project running.

**Comment by Faagerholm** [comment]
Has been deployed to two different servers, we also have two QA servers. I think it's time to close this issue. 🥂
