### ISSUE TITLE
bug: frontpage links in news are white

### ISSUE THREAD

**Issue by Faagerholm** [Datateknologerna-vid-Abo-Akademi/date-website#81]
**Describe the bug**  
In a news article, any direct link is white and therefore invisible.

**Screenshots**  
![image](https://user-images.githubusercontent.com/26307354/77292341-ca45b580-6ce8-11ea-817f-d180fabfdbbb.png)

**Comment by Faagerholm** [comment]
In the detailed view, the link could also be colored in a different bright color.

**Comment by Faagerholm** [comment]
This was an easy fix, just edit the color in CKeditor (admin panel) of the link.

**Comment by andreedd** [comment]
Also fixed the default color to page link colors, you can still change the color from ckeditor tho
