### ISSUE TITLE
fix: Scrolling past bottom/top of hamburger menu scrolls the web page (the background), looks off

### ISSUE THREAD

**Issue by oj-lappi** [Datateknologerna-vid-Abo-Akademi/date-website#86]
If I scroll the menu to the bottom, but keep scrolling, the webpage scrolls instead.

This should be fixable in css (I think).

**Describe the solution you'd like**  
No scrolling, also we could possibly make the font in the mobile menu a little bit smaller.

**Additional context**

**Comment by andreedd** [comment]
Background is now fixed when mobile nav is visible.
Text is a little bit smaller.
