### ISSUE TITLE
Merge/Create new database for users

### ISSUE THREAD

**Issue by Faagerholm** [Datateknologerna-vid-Abo-Akademi/date-website#9]
Either use old database with users (should be cleaned up) or create a new one and add users (abo.fi-address) so people can sign in.

**Comment by LinAnt** [comment]
Definately go with a new DB, the old one on special has some weird ass encoding :)

**Comment by siikasmaa** [comment]
Should we just go with PostgreSQL?

**Comment by LinAnt** [comment]
Postgres is a beast :)

**Comment by Faagerholm** [comment]
Won't extract old information. This will require some manual work instead.
